version: "3"
services:
  backend:
    build: 
      context: ../backend
    restart: always
    expose:
      - "3000"
    networks:
      private: 
    environment:
      - APP_FRONT_DOMAIN
      - APP_API_DOMAIN

  web:
    build: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - private
      - public
    volumes:
      - ../www:/etc/nginx/www
      - ./certificates:/etc/nginx/certificates
    environment:
      - APP_FRONT_DOMAIN
      - APP_API_DOMAIN

networks:
  public: 
  private: 